package com.gosuraksha.app.ui.main

import android.content.Context
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.Shield
import androidx.compose.material3.Icon
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties

// ── SharedPreferences helpers ─────────────────────────────────────────────────

private const val PREFS_NAME = "cyber_card_prefs"
private const val KEY_DISCLAIMER = "disclaimer_accepted_v1"

fun hasAcceptedCyberCardDisclaimer(context: Context): Boolean =
    context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        .getBoolean(KEY_DISCLAIMER, false)

fun markCyberCardDisclaimerAccepted(context: Context) {
    context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        .edit().putBoolean(KEY_DISCLAIMER, true).apply()
}

// ── Dialog composable ─────────────────────────────────────────────────────────

@Composable
fun CyberCardDisclaimerDialog(
    isDark: Boolean,
    onAccept: () -> Unit
) {
    val bg      = if (isDark) Color(0xFF0F1A10) else Color(0xFFFFFFFF)
    val text1   = if (isDark) Color(0xFFD4EDD9) else Color(0xFF0D1F14)
    val text2   = if (isDark) Color(0xFF6BAA80) else Color(0xFF5A8A6A)
    val green   = Color(0xFF2EC472)
    val divCol  = if (isDark) Color(0x1AFFFFFF) else Color(0x1A000000)

    Dialog(
        onDismissRequest = { /* not dismissible — must tap button */ },
        properties       = DialogProperties(dismissOnClickOutside = false, dismissOnBackPress = false)
    ) {
        Surface(
            color  = bg,
            shape  = RoundedCornerShape(24.dp),
            tonalElevation = 0.dp,
            modifier = Modifier.fillMaxWidth()
        ) {
            Column(
                modifier            = Modifier.padding(24.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                // Icon badge
                Box(
                    modifier = Modifier
                        .size(56.dp)
                        .background(green.copy(alpha = 0.12f), CircleShape),
                    contentAlignment = Alignment.Center
                ) {
                    Icon(
                        Icons.Rounded.Shield, null,
                        tint     = green,
                        modifier = Modifier.size(26.dp)
                    )
                }

                // Title
                Text(
                    "About Your Cyber Safety Score",
                    color      = text1,
                    fontSize   = 17.sp,
                    fontWeight = FontWeight.Bold,
                    textAlign  = TextAlign.Center
                )

                // Divider
                Box(modifier = Modifier.fillMaxWidth().height(1.dp).background(divCol))

                // Body
                Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                    DisclaimerParagraph(
                        text2,
                        "This Cyber Card is a personal safety score generated by GO Suraksha based on your activity and risk signals."
                    )
                    DisclaimerBullet(text2, green, "It is NOT a government-issued identity.")
                    DisclaimerBullet(text2, green, "It cannot be used for loans, verification, or official purposes.")
                    DisclaimerParagraph(
                        text2,
                        "This is only for your personal awareness and digital safety."
                    )
                }

                // Divider
                Box(modifier = Modifier.fillMaxWidth().height(1.dp).background(divCol))

                // CTA
                Surface(
                    onClick       = onAccept,
                    color         = green,
                    shape         = RoundedCornerShape(14.dp),
                    modifier      = Modifier.fillMaxWidth()
                ) {
                    Text(
                        "I Understand",
                        color      = Color.White,
                        fontSize   = 15.sp,
                        fontWeight = FontWeight.SemiBold,
                        textAlign  = TextAlign.Center,
                        modifier   = Modifier.padding(vertical = 14.dp)
                    )
                }
            }
        }
    }
}

@Composable
private fun DisclaimerParagraph(color: Color, text: String) {
    Text(
        text      = text,
        color     = color,
        fontSize  = 13.sp,
        lineHeight = 19.sp,
        textAlign = TextAlign.Center
    )
}

@Composable
private fun DisclaimerBullet(textColor: Color, bulletColor: Color, text: String) {
    Row(
        horizontalArrangement = Arrangement.spacedBy(8.dp),
        verticalAlignment     = Alignment.Top
    ) {
        Box(
            modifier = Modifier
                .padding(top = 6.dp)
                .size(6.dp)
                .background(bulletColor, CircleShape)
        )
        Text(
            text      = text,
            color     = textColor,
            fontSize  = 13.sp,
            lineHeight = 19.sp
        )
    }
}
